#!/bin/bash
# Quick Start - Unit Tests

echo "🧪 Pokemon MCP + AP2 - Unit Tests"
echo "=================================="
echo ""
echo "📊 Estado: ✅ 15 tests | 80% cobertura"
echo ""
echo "🚀 Comandos rápidos:"
echo ""
echo "  ./run_tests.sh              # Ejecutar todos los tests"
echo "  ./run_tests.sh --coverage   # Con reporte de cobertura"
echo "  ./run_tests.sh --quick      # Para en primer error"
echo "  ./run_tests.sh --verbose    # Modo detallado"
echo ""
echo "📝 Tests específicos:"
echo ""
echo "  pytest test_inventory_update.py -v"
echo "  pytest test_e2e_flow.py -v"
echo ""
echo "📚 Documentación completa:"
echo ""
echo "  cat SUMMARY.md              # Resumen completo"
echo "  cat README.md               # Guía de uso"
echo ""
